export const narrative = {
  "chapter1": [
    "B.R. International started in 2018, but the idea behind it came before there was a company. At the time, I already had experience in international logistics and trade. I also had some familiarity with plastics through my family background, so the industry itself was not completely foreign to me. While spending time looking at the U.S. plastics market, particularly around Houston, I began noticing something that looked simple but commercially interesting.",
    "There were manufacturers, recyclers, and processors in the United States producing or handling industrial plastic materials. At the same time, customers in Korea and other Asian markets were actively looking for material. There was supply on one side and demand on the other.",
    "The difficult part was everything in between. Someone still had to understand the material, find the supplier, negotiate the price, arrange domestic transportation, book containers, manage export documentation, coordinate international shipping, communicate with the customer, collect payment, and make sure the transaction still made economic sense after all of those costs. That was where I thought I could create value.",
    "I understood logistics. I understood enough about the material to start learning the business seriously. And I could operate between the U.S. and Asian business environments.",
    "I remember thinking, in very simple terms: IF I UNDERSTAND THE MATERIAL, AND I UNDERSTAND THE LOGISTICS, WHY CAN'T I BUILD THE BRIDGE MYSELF? But seeing an opportunity and being able to finance it were two different things.",
    "I did not have a large amount of working capital. I did not have an established supplier network. I did not have a large organization behind me.",
    "So I could not start by building a warehouse full of inventory and hoping customers would come. I had to find a way to test the opportunity with the resources I actually had."
  ],
  "chapter2": [
    "I started small. The first real test was approximately one or two containers. At that stage, I was not trying to prove that I could build a large company.",
    "I was trying to answer a much more basic question: Can this transaction actually work from beginning to end? Finding material at an attractive price was only the first step.",
    "The material had to match what the customer needed. Domestic freight had to work. The container had to be loaded.",
    "Export and international shipping had to be executed correctly. The customer had to accept the material. Payment had to be controlled.",
    "And after all of that, there still had to be enough margin left to justify doing it again. Those early shipments gave me something more useful than a business plan. They gave me real-world validation.",
    "The model worked. But the next constraint was obvious. Working capital.",
    "I did not have enough capital to buy significant amounts of material first, hold the inventory, ship it internationally, and then wait for customers to pay. So the early commercial model was built around prepayment. Some of the first customers came through relationships connected to my family's history in the plastics business.",
    "When customers in Korea learned that I was sourcing material in the United States, some were willing to work with me. The arrangement was straightforward. The customer paid first.",
    "I used that money to purchase the material in the United States. Then I handled the freight, container, export process, and delivery.",
    "At the beginning, trust was the real currency of the company. The customer had to trust me enough to send money before receiving the material. My responsibility was to make sure that trust was justified.",
    "Every successful shipment made the next transaction easier. Customers ordered again. Some customers introduced other customers.",
    "The business started growing through execution rather than through advertising or a large sales organization. The early growth cycle was simple: TRUST → EXECUTION → REPEAT BUSINESS → REFERRALS → GROWTH",
    "That became the foundation of B.R. International."
  ],
  "chapter3": [
    "Once the early transactions proved that the model could work, the decision became more personal. Testing a few shipments while still having another source of stability was one thing. Building a company around the opportunity was something different.",
    "I decided to leave my previous work in Orange County and move to Texas. Houston was the first destination. It made sense on paper because Houston had a major petrochemical and plastics industry base, and I believed being close to that ecosystem would help me develop the business.",
    "I spent approximately nine months there. During that period, I continued learning the market, looking for material, meeting people, and trying to understand where the company should actually be based. Eventually I concluded that Houston was not the best long-term location for the business I was trying to build.",
    "I moved to Dallas and established the operating base there. That move represented an important change in how I was thinking. The question was no longer:",
    "CAN I MAKE MONEY ON A TRANSACTION? The question had become: CAN I BUILD A REPEATABLE BUSINESS?"
  ],
  "chapter4": [
    "Once customer demand started developing, the hardest problem became supply. I did not begin with a ready-made supplier list. I had to figure out where the material actually came from.",
    "I started with online research. I searched for recyclers, manufacturers, processors, and industrial companies that might generate the types of plastics my customers needed. Then I called them.",
    "Most calls did not immediately turn into business. Some companies were not interested. Some already had relationships.",
    "Some would talk but had nothing available. But when someone was willing to meet, I went. A lot of these facilities were not located next to major airports or downtown business districts.",
    "I might fly into a city, rent a car, drive another hour or two, meet someone for only ten or twenty minutes, and then travel back. The meeting itself could be very short. The trip was not.",
    "During the most aggressive supplier-development period, I estimate that I was traveling around fifteen days in a normal month. I did that for approximately a year. It was repetitive work.",
    "SEARCH. CALL. TRAVEL.",
    "MEET. FOLLOW UP. COME BACK.",
    "PROVE THAT I WOULD ACTUALLY DO WHAT I SAID. Over time, those individual conversations started becoming relationships. Eventually B.R. International had developed a U.S. supplier network of approximately 30 to 40 companies.",
    "But the most important thing I learned during that period was not how to build a supplier list. It was how to build a supplier relationship. One relationship in particular changed the way I approached supplier development.",
    "That was Dura-Line."
  ],
  "chapter5": [
    "Dura-Line was a large pipe manufacturer. B.R. International was still a small recycling company. From their perspective, there was no obvious reason to prioritize me.",
    "At the beginning, I could not get a meaningful meeting with the people who controlled the material. So I kept going back. Approximately every one or two weeks, I would return.",
    "Sometimes nothing happened. Sometimes I only had a very short interaction. The purpose was not to force a deal.",
    "It was to become familiar enough that eventually someone would give me a real conversation. I continued doing that for roughly three months. Eventually, I had an opportunity to speak more seriously with a manager.",
    "That conversation became important because I did not start by asking the question recyclers normally ask: HOW MUCH DO YOU WANT FOR THE MATERIAL? Instead, I asked:",
    "WHAT IS YOUR BIGGEST PROBLEM WITH THIS MATERIAL? The answer changed how I saw the opportunity. Dura-Line had bulky pipe scrap.",
    "The material had value, but physically handling it was difficult. Large pipe scrap takes up space. It is awkward to move.",
    "It is inefficient to load. Traditional transportation and container methods can make the economics unattractive. So the supplier's problem was not simply:",
    "\"Who will pay the highest price for this scrap?\" They also had an operational problem: \"How do we remove this material efficiently?\"",
    "That gave me something different to solve. Instead of focusing only on purchasing price, I started thinking about the logistics. One practical solution involved using open-top containers so the bulky pipe material could be loaded more easily with forklifts and removed with less handling difficulty.",
    "That changed the nature of the relationship. I was no longer only asking Dura-Line to sell something to me. I was helping solve a problem they already had.",
    "I also did not begin by demanding access to the easiest or most valuable material. I was willing to start with the difficult material. Then I focused on execution.",
    "If we said we would remove material, we removed it. If there was a problem, I dealt with it. Over time, trust increased.",
    "The relationship developed over approximately one to one-and-a-half years and eventually became much deeper. As that happened, B.R. International gained access to additional and more valuable material opportunities. The lesson stayed with me long after the individual transactions.",
    "Before Dura-Line, it was easy to think about supplier development mainly in terms of price, volume, and availability. After Dura-Line, I thought about it differently. A strong supplier relationship is not only a purchasing relationship.",
    "If I can make the supplier's operation easier, reduce a problem, create reliability, or remove something they do not want to manage themselves, then I am creating value before I ever begin negotiating what I want. That became one of the most important principles I carried forward from B.R. International."
  ],
  "chapter6": [
    "As B.R. International grew, the trading model was producing business, but I could also see where it was weak. Supplier development required constant travel. Supply was fragmented.",
    "Some materials were bulky and expensive to transport in their original form. A material could look cheap at the factory and still become a bad transaction once trucking, container utilization, and international freight were included. The company was also highly dependent on export markets.",
    "That meant the business was exposed to freight conditions and international market changes that I could not control. COVID made some of those weaknesses much more visible. I began thinking about whether B.R. International could create more value by doing more than moving material from one company to another.",
    "If we could process the material ourselves, we could potentially change the economics. Bulky material could be reduced in size. Mixed or difficult material could potentially be processed.",
    "More value could be created before the product was shipped. That thinking led to the biggest strategic transition in the company's history: TRADING → PROCESSING → MANUFACTURING",
    "B.R. International took over a small recycling operation of approximately 6,000 square feet. At the time, I saw this as the next stage of the business. In reality, it was the beginning of an entirely different learning curve."
  ],
  "chapter7": [
    "The first facility was not a polished manufacturing operation waiting for us to take over. It was small. The layout needed work.",
    "The equipment was limited. And some of the machinery had operational problems. One Chinese machine had never been properly put into production because its electrical requirements did not match the power configuration available in the facility.",
    "I did not have an electrical engineering background. I did not have formal machinery training. But the machine sitting there without running was not going to solve itself.",
    "So I started by trying to understand the actual problem. I learned what the machine required. I looked at the available power.",
    "I identified the transformer issue. Then I found and hired a professional electrician who could safely complete the work. We installed the correct solution and brought the equipment into operation.",
    "At the same time, I began reorganizing the warehouse and learning how material should move through a production environment. This was completely different from trading. In trading, I could evaluate a transaction through price, freight, quality, and customer demand.",
    "Inside a factory, I had to think about: where material entered, where it was stored,",
    "how it moved, how the machine processed it, how operators worked,",
    "where bottlenecks appeared, how downtime affected output, and how production problems eventually became commercial problems.",
    "Processing also changed the economics of the material itself. Some bulky plastics that were difficult or too expensive to ship in their original form could now be reduced or processed into a more transport-efficient form. That meant B.R. International could handle opportunities that did not make sense under the pure trading model."
  ],
  "chapter8": [
    "Once the first processing operation started working, the next step seemed obvious to me at the time. If a small amount of equipment created value, then more equipment should create more value. If more capacity allowed us to process more material, then more capacity should create more revenue and more profit.",
    "The logic looked simple: MORE EQUIPMENT → MORE CAPACITY → MORE MATERIAL → MORE REVENUE → MORE PROFIT So I expanded.",
    "The operation grew from approximately 6,000 square feet to approximately 24,000 square feet. We added more equipment. Shredders.",
    "Crushers. Washing equipment. More automated processing capability.",
    "Physically, the company looked much more capable. But I had underestimated what manufacturing scale actually required. Machines do not only need to be purchased.",
    "They need to be operated correctly. They need preventive maintenance. Blades wear down.",
    "Settings matter. Power matters. Spacing matters.",
    "Material flow matters. Repairs matter. Downtime matters.",
    "And most importantly, someone needs to have the technical knowledge to manage all of those things systematically. I had expanded the physical capacity of the company faster than I had expanded its technical capability. I also had not built strong enough plant-level technical leadership early enough.",
    "When something went wrong, the problem often came back to me. Because I was the owner, my instinct was to solve it. So I learned.",
    "I took machines apart. I studied how they worked. I troubleshot problems.",
    "I repaired equipment. I reinstalled components. I spent a significant amount of time over roughly two years becoming much more hands-on technically than I had ever expected.",
    "There is value in that experience. It taught me how operations really work. But it also exposed the weakness in the way I was scaling the company.",
    "The founder becoming better at fixing machines was not the same thing as the company developing technical capability.",
    "Looking back, I do not think entering processing and manufacturing was necessarily the mistake. The mistake was the speed and sequence of the expansion. I increased physical capacity before I had built enough technical leadership, systems, maintenance capability, and organizational structure around it.",
    "That distinction became one of the most important lessons of the entire seven-year experience."
  ],
  "chapter9": [
    "By its mature stage, B.R. International was no longer a simple trading company. The business had to manage multiple functions at the same time. We had a U.S. supplier network.",
    "We had customers across Asian markets. We were sourcing material. Negotiating commercial terms.",
    "Managing domestic freight. Planning containers. Handling exports.",
    "Managing customer payments. Controlling working capital. Processing material.",
    "Operating machinery. Managing quality. Managing employees.",
    "Solving production problems. And responding when something went wrong somewhere in that chain. At peak, B.R. International had approximately 30 to 40 U.S. supplier relationships and approximately 15 employees.",
    "The company had developed its own processing and manufacturing capability. Normal peak-year revenue was approximately $3 million. But the biggest change was not the revenue number.",
    "The biggest change was how I understood business. When I started, I thought primarily about transactions. Buy correctly.",
    "Sell correctly. Move the product. Make a margin.",
    "By this stage, I understood that every part of the company affected every other part. A supplier problem could become a customer problem. A machine problem could become a cash-flow problem.",
    "A quality problem could become a relationship problem. A payment problem could become a sourcing problem. A hiring problem could become a production problem.",
    "Business was no longer a sequence of independent functions. It was a system."
  ],
  "eva": [
    "One opportunity involved EVA material. The supply side looked attractive. But by this point, I had learned that an attractive purchase price did not automatically mean there was a good business opportunity.",
    "So before committing to the material, I worked from the other direction. I looked at the customer market first. I investigated demand in Malaysia.",
    "I confirmed the price range customers were willing to support. Then I worked backward. What price could we sell at?",
    "What would freight cost? What margin would remain? What purchase price would make the transaction work?",
    "Only after understanding the likely exit did we commit to the buy. The resulting business eventually reached approximately 20 containers and more than 400 tons. The volume was meaningful.",
    "But the more important result was the decision-making principle behind it.",
    "A sourcing opportunity is not automatically a business opportunity. The downstream economics have to support the upstream decision."
  ],
  "abs": [
    "Another transaction involved material that the supplier represented as ABS. Something did not feel right to me. By then, I had spent years handling different plastics.",
    "I was not a laboratory technician or polymer scientist, but I had developed practical material knowledge through repeated exposure. The physical behavior of this material did not match what I expected from ABS. Its burn behavior and smell also made me question the identification.",
    "My suspicion was that the material might actually be PS or HIPS. I did not assume that my judgment was automatically correct. I separated samples and asked for additional verification through the customer and professional testing resources.",
    "The later verification supported my concern. The experience reinforced something important for me. Commercial decisions become stronger when the person making them understands the product.",
    "A supplier label is useful information. But when the product itself is telling you something different, verification matters."
  ],
  "customerDefault": [
    "B.R. International normally required full prepayment before shipment. That discipline existed for a reason. In one transaction, I relaxed it.",
    "The customer paid approximately a 50% deposit. We shipped four containers. Then the customer disappeared and defaulted.",
    "The cargo was already moving internationally. At that point, the company had immediate financial exposure. It would be easy to tell this story only as a crisis-recovery success.",
    "But that would ignore the most important part. The first mistake was mine. I had weakened a payment rule that existed specifically to protect the company.",
    "Once that mistake had already been made, the question became: How much of the situation can I still recover? I immediately started using our market network to find another buyer.",
    "We identified an alternative customer in Southeast Asia. The cargo was redirected. The replacement transaction required approximately a 15 to 20 percent discount.",
    "There were also additional diversion and transshipment costs. It was not the outcome I wanted. But it prevented a much larger potential loss.",
    "Risk management is not only about being good at solving emergencies. The better form of risk management is maintaining the discipline that prevents unnecessary emergencies in the first place."
  ],
  "chapter11": [
    "When B.R. International was small, I could personally stay close to almost everything. I knew the customers. I knew the suppliers.",
    "I could make sourcing decisions. I could negotiate. I could deal with logistics problems.",
    "If a customer had an issue, I became involved. If a machine broke, I became involved. If production had a problem, I became involved.",
    "That hands-on approach was one of the reasons I was able to build the company from zero. But the same behavior became harder to sustain as the company became larger. More revenue meant more transactions.",
    "More transactions meant more payment exposure. More processing meant more equipment. More equipment meant more maintenance.",
    "More employees meant more management. More suppliers and customers meant more relationships that needed attention. The complexity was growing faster than the systems around it.",
    "I had successfully built a company that could do more. But I had not built enough structure to make sure the company did not depend so heavily on me personally. That became one of the most uncomfortable but valuable lessons from the experience.",
    "Being willing to solve every problem helped me build the company. Learning that I should not be the permanent solution to every problem changed how I think about leadership."
  ],
  "chapter12": [
    "By 2025, the environment around the business had changed significantly. The recycling market had weakened. Virgin resin prices were low enough to put pressure on recycled-material economics.",
    "Demand and margins became more difficult. At the same time, the manufacturing side of the business continued to require maintenance, repair, technical attention, and capital. Machine failures created downtime.",
    "Factory economics became harder to justify. The operational burden was increasing while the commercial environment was becoming less attractive. For a long time, my instinct had always been to solve the next problem.",
    "Find another customer. Find another supplier. Repair the machine.",
    "Change the process. Work harder. That mindset had helped me survive many difficult periods.",
    "But eventually I had to ask a different question. Not: HOW DO I KEEP THIS GOING?",
    "But: DOES CONTINUING TO PUT MORE MONEY AND MORE OF MYSELF INTO THIS BUSINESS STILL MAKE ECONOMIC SENSE? That was a difficult question because B.R. International was not just an investment.",
    "I had spent seven years building it. It represented relationships. Employees.",
    "Customers. Suppliers. Money.",
    "Time. Identity. And an enormous amount of personal effort.",
    "Stopping meant accepting that those seven years did not guarantee that the next year would make sense. Eventually I decided to stop continuing to consume cash and personal capacity simply because I had already invested so much.",
    "That decision changed the way I think about persistence. Persistence is valuable when the fundamentals still justify continuing. But persistence without reassessment can become attachment.",
    "Sometimes the disciplined decision is to continue. Sometimes the disciplined decision is to stop."
  ],
  "final": [
    "B.R. International taught me how to identify an opportunity and turn it into a functioning business. It taught me how to build supplier relationships from nothing, work across markets, manage commercial risk, solve operational problems, and make decisions when there was no established playbook. It also showed me the limits of founder-led execution.",
    "The company grew because I was willing to get involved in almost everything. Eventually, that same dependence became part of the problem. That combination — what worked, what failed, what I solved, and what I would do differently — is why the seven-year experience remains one of the most important parts of how I think about business today."
  ]
};
