import styles from "./case.module.css";

const supplierSteps=["SEARCH","CALL","VISIT","FOLLOW UP","PROVE RELIABILITY","BUILD THE RELATIONSHIP"];
const functions=["SUPPLIER DEVELOPMENT","U.S. SOURCING","CUSTOMER DEVELOPMENT","INTERNATIONAL SALES","LOGISTICS","CONTAINER PLANNING","EXPORT OPERATIONS","CASH FLOW","PAYMENT RISK","PROCESSING","MANUFACTURING","QUALITY","EQUIPMENT","EMPLOYEES","PROBLEM SOLVING"];
const pressures=["WEAK RECYCLING MARKET","LOW VIRGIN RESIN PRICES","MARGIN PRESSURE","MACHINE FAILURES","FACTORY ECONOMICS","OPERATIONAL COMPLEXITY","FOUNDER WORKLOAD"];
const solved=[
 ["WORKING CAPITAL","I started without enough capital to carry a traditional inventory-heavy model, so the early business used customer prepayment to make transactions executable."],
 ["SUPPLIER DEVELOPMENT","I built an approximately 30–40-company U.S. supplier network through research, cold calls, repeated travel, factory visits, follow-up, and consistent execution."],
 ["SUPPLIER OPERATIONS","With suppliers such as Dura-Line, I learned to create value by solving handling and logistics problems rather than focusing only on purchase price."],
 ["CROSS-BORDER EXECUTION","I connected U.S. sourcing with Asian customers through pricing, domestic logistics, containers, documentation, export, payment, and customer coordination."],
 ["PROCESSING ECONOMICS","Moving into processing allowed the company to handle bulky materials that were difficult to move economically in their original form."],
 ["TECHNICAL PROBLEM SOLVING","I learned enough about machinery, power requirements, production flow, and equipment failure to diagnose problems and coordinate professional solutions when required."],
 ["MARKET VALIDATION","The EVA business reinforced the discipline of validating downstream demand and target economics before committing capital upstream."],
 ["MATERIAL JUDGMENT","Years of hands-on exposure allowed me to question material identification when product behavior did not match the supplier description and then seek proper verification."],
 ["COMMERCIAL CRISIS RESPONSE","When a customer defaulted after four containers had shipped, I used the company’s network to redirect the cargo and reduce the potential loss."],
 ["SCALE MANAGEMENT","I experienced directly what happens when physical capacity grows faster than technical capability, management systems, and organizational structure."],
 ["CAPITAL DISCIPLINE","In the end, I had to decide whether continuing to invest was economically justified rather than allowing seven years of sunk cost to decide for me."],
];
const lessons=[
 ["01","START SMALL. VALIDATE BEFORE SCALING.","The company began through real transactions rather than assumptions. Testing small made it possible to understand the economics before making a larger commitment."],
 ["02","CREATE VALUE BEFORE ASKING FOR VALUE.","Dura-Line taught me that supplier relationships become much stronger when I begin with the supplier’s operational problem rather than my purchasing objective."],
 ["03","UNDERSTAND THE EXIT BEFORE COMMITTING TO THE BUY.","The EVA transaction reinforced the importance of validating customer demand, price, and downstream economics before committing capital."],
 ["04","CASH FLOW AND COMMERCIAL DISCIPLINE MATTER AS MUCH AS REVENUE.","The four-container default showed me how quickly one relaxed payment rule can create unnecessary exposure."],
 ["05","CAPABILITY MATTERS MORE THAN CAPACITY.","The factory expansion taught me that machines, square footage, and production capacity do not automatically create the technical organization required to operate them."],
 ["06","SYSTEMS HAVE TO SCALE BEFORE COMPLEXITY DOES.","As the company grew, suppliers, customers, equipment, people, logistics, cash flow, and risk became increasingly connected."],
 ["07","A BUSINESS CANNOT DEPEND ON ONE PERSON FOREVER.","My willingness to personally solve problems helped build B.R. International. It was not a sustainable long-term operating model."],
 ["08","PERSISTENCE AND SUNK COST ARE NOT THE SAME THING.","Knowing when to keep going matters. Knowing when the fundamentals no longer justify continuing matters too."],
];
function Label({children}){return <p className={styles.label}>{children}</p>}
function Flow({items}){return <div className={styles.arrowFlow}>{items.map((x,i)=><div className={styles.flowPair} key={x}><span>{x}</span>{i<items.length-1&&<b>→</b>}</div>)}</div>}
function Copy({children}){return <div className={styles.deepCopy}>{children}</div>}
export const metadata={title:"B.R. International USA LLC — Brandon Baek",description:"The complete seven-year story of building B.R. International from cross-border trading into processing and manufacturing."};

export default function Case(){return <main className={styles.casePage}>
 <header className={styles.header}><a className={styles.brand} href="/"><strong>BRANDON BAEK</strong><span>GLOBAL BUSINESS · SUPPLY CHAIN</span></a><nav className={styles.nav}><a href="/">Home</a><a href="/about">About</a><a className={styles.active} href="/work">Work</a><a href="/contact">Contact</a></nav></header>
 <div className={styles.journey}>
  <section className={`${styles.section} ${styles.hero}`}><div className={styles.heroMain}><Label>CASE 01 / B.R. INTERNATIONAL</Label><p className={styles.company}>B.R. INTERNATIONAL USA LLC <span>2018—2025</span></p><h1>FROM ZERO<br/><em>TO A REAL BUSINESS.</em></h1><Copy><p>B.R. International began in 2018 as a small cross-border plastics trading business.</p><p>What started with limited capital and a simple opportunity between U.S. material supply and Asian demand eventually became a company operating across sourcing, supplier development, logistics, processing, manufacturing, customer development, and international trade.</p><p>Over seven years, the business grew from a few early transactions into a multi-million-dollar operation with an established U.S. supplier network, customers across Asian markets, approximately 15 employees at peak, and its own processing and manufacturing capabilities.</p><p>This case is not only about how the company grew. It is also about what happened when growth became more complex than the organization was ready to support.</p></Copy></div><aside className={styles.heroMeta}><p>FOUNDER / CEO</p><p>CROSS-BORDER PLASTICS</p><p>TRADING → PROCESSING / MANUFACTURING</p><p>U.S. → ASIA</p></aside><div className={styles.stats}><div><strong>2018—2025</strong><span>SEVEN-YEAR JOURNEY</span></div><div><strong>~30–40</strong><span>U.S. SUPPLIERS</span></div><div><strong>~15</strong><span>EMPLOYEES AT PEAK</span></div><div><strong>~$3M</strong><span>NORMAL PEAK-YEAR REVENUE</span></div></div></section>

  <section className={`${styles.section} ${styles.beginning}`}><div><Label>01 / THE BEGINNING</Label><h2>I SAW AN OPPORTUNITY.<br/><em>BUT I DIDN’T HAVE MUCH<br/>TO START WITH.</em></h2><Narrative id="chapter2"/><Narrative id="chapter1"/></div><Copy><p>Before starting B.R. International, Brandon already had experience in logistics and international trade and some familiarity with plastics through his family background.</p><p>While exploring the U.S. plastics market, he noticed a practical gap: industrial plastic materials were available from American manufacturers, recyclers, and processors, while customers in Korea and other Asian markets were actively looking for material.</p><p>The opportunity looked simple from a distance—U.S. supply on one side and Asian demand on the other. In between were material identification, supplier relationships, pricing, freight, containers, export documentation, customer trust, payment, working capital, and transaction risk.</p><p>Brandon believed his material familiarity, logistics experience, and ability to work between U.S. and Asian business environments could create value in that gap. The largest constraint was capital: he could not buy large inventories first and wait for customers to pay later.</p></Copy><blockquote>THE OPPORTUNITY WAS REAL.<br/><strong>THE BUSINESS MODEL HAD TO FIT THE RESOURCES AVAILABLE.</strong></blockquote></section>

  <section className={styles.section}><Label>02 / VALIDATION</Label><h2>BEFORE BUILDING A COMPANY,<br/><em>I NEEDED TO KNOW IF THE TRANSACTION WORKED.</em></h2><Copy><p>The company did not begin with a factory, warehouse, or large investment. Approximately one or two containers were used to test whether the complete model could work under real conditions.</p><p>The test was larger than buying and reselling material. Could Brandon find reliable supply? Would the economics survive freight and handling? Could export logistics be executed correctly? Would the customer accept the product? Could payment timing and risk be controlled?</p><p>The early shipments proved the commercial model could work. Working capital remained the constraint, so B.R. International used a prepayment-based model: customers paid before the company purchased the material.</p></Copy><Flow items={["CUSTOMER PREPAYMENT","MATERIAL PURCHASE","DOMESTIC FREIGHT","CONTAINER / EXPORT","ASIAN CUSTOMER","COMPLETED TRANSACTION"]}/><Copy><p>This structure allowed transactions without carrying the full inventory burden. More importantly, every shipment that arrived as promised created trust. Customers placed additional orders, and some introduced other customers.</p></Copy><Flow items={["TRUST","EXECUTION","REPEAT BUSINESS","REFERRALS","GROWTH"]}/></section>

  <section className={styles.section}><Label>THE COMMITMENT / MOVING TO TEXAS</Label><h2>THE TEST WORKED.<br/><em>NOW I HAD TO DECIDE WHETHER I REALLY BELIEVED IN IT.</em></h2><Narrative id="chapter3"/><Copy><p>After confirming that the model worked, Brandon left his previous work in Orange County and committed to building the business.</p><p>Houston was the first destination because of its concentration of petrochemical and plastics businesses. After approximately nine months, he concluded it was not the best long-term base for the type of business he wanted to build.</p><p>He moved to Dallas and established B.R. International’s operating base. The question had changed from “Can I complete a profitable transaction?” to “Can I build a repeatable business?”</p></Copy><Flow items={["ORANGE COUNTY","HOUSTON / ~9 MONTHS","DALLAS / OPERATING BASE"]}/></section>

  <section className={`${styles.section} ${styles.suppliers}`}><Label>03 / BUILDING SUPPLY</Label><h2>CUSTOMERS WERE ONLY USEFUL<br/><em>IF I COULD FIND THE MATERIAL.</em></h2><Narrative id="chapter4"/><Copy><p>As customer demand developed, sourcing became the hardest problem. B.R. International had no established U.S. supplier network. Brandon had to build one.</p><p>He researched recyclers, manufacturers, processors, and industrial facilities online, then cold-called them. If someone agreed to meet, he traveled—often to facilities far from major airports. A ten- or twenty-minute meeting could require a full day or more.</p><p>During the most intensive period, Brandon estimates that roughly 15 days of a typical month were spent traveling to suppliers. This continued for approximately a year.</p></Copy><div className={styles.loop}>{supplierSteps.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span></div>)}</div><div className={styles.networkResult}><span>BUILT OVER TIME</span><strong>~30–40</strong><span>U.S. SUPPLIERS</span></div><Copy><p>One relationship became especially important because it changed Brandon’s approach to supplier development.</p></Copy><div className={styles.zoom}><strong>DURA-LINE</strong><i/></div></section>

  <section className={`${styles.section} ${styles.duraline}`}><Label>STORY MOMENT / DURA-LINE</Label><h2>THEY WOULDN’T<br/>MEET ME.</h2><Narrative id="chapter5"/><Copy><p>Dura-Line was a large pipe manufacturer. B.R. International was still a small recycling company, and Brandon could not initially gain meaningful access to the people who controlled the material.</p><p>Instead of giving up, he returned approximately every one or two weeks. Sometimes there was no real meeting; the purpose was to remain visible and create familiarity. This continued for roughly three months.</p><p>Eventually, Brandon had an opportunity to speak more seriously with a manager. He did not begin with, “What price can you give me?” He asked, “What is your biggest problem with this material?”</p></Copy><div className={styles.question}><small>THE QUESTION THAT CHANGED THE RELATIONSHIP</small><blockquote>“WHAT IS YOUR BIGGEST PROBLEM<br/>WITH THIS MATERIAL?”</blockquote></div><Copy><p>The company had bulky pipe scrap that was difficult to move and handle efficiently. The material had value, but its size created a practical logistics and removal problem.</p><p>Brandon developed an open-top-container approach so the pipe could be loaded more easily with forklifts and removed with less handling difficulty. The first value B.R. International created was not a better price. It was a better solution.</p><p>He started with the difficult material rather than demanding access to the most attractive streams. As the company executed consistently, trust increased. Over approximately one to one-and-a-half years, the relationship deepened and later opened access to additional, more valuable opportunities.</p><p>Dura-Line changed Brandon’s understanding of supplier development: the strongest supplier relationships are built by creating operational value, not simply negotiating a purchase.</p></Copy><blockquote className={styles.principle}>BEFORE ASKING WHAT A SUPPLIER CAN GIVE ME,<br/><strong>I ASK WHAT PROBLEM I CAN SOLVE FOR THEM.</strong></blockquote></section>

  <section className={`${styles.section} ${styles.pivot}`}><Label>04 / THE PIVOT</Label><h2>TRADING WAS WORKING.<br/><em>BUT IT HAD LIMITS.</em></h2><Narrative id="chapter6"/><Copy><p>The business was growing, but Brandon saw structural limitations. It depended heavily on travel. Supply was fragmented. Bulky materials were expensive to transport. Some opportunities looked attractive at the supplier level but became uneconomic after freight and handling.</p><p>The company was also heavily dependent on export markets. COVID increased pressure on those weaknesses. Brandon began asking whether B.R. International could create more value by performing part of the processing itself.</p></Copy><Flow items={["TRADING","PROCESSING","MANUFACTURING"]}/><div className={styles.facility}><strong>~6,000</strong><span>SQ FT</span><p>THE FIRST PROCESSING OPERATION</p></div></section>

  <section className={styles.section}><Label>BUILDING PROCESSING CAPABILITY</Label><h2>THE COMPANY STOPPED BEING ONLY A TRADER.<br/><em>IT HAD TO LEARN HOW TO OPERATE.</em></h2><Narrative id="chapter7"/><Copy><p>The small facility was not a ready-made manufacturing operation. It had limited equipment and operational problems.</p><p>One Chinese machine had never been properly brought into operation because its electrical requirements did not match the facility’s available power configuration. Brandon had no electrical or machinery background, so he had to identify the real problem and find the people and equipment required to solve it.</p><p>The solution involved identifying the correct transformer configuration and hiring a professional electrician to complete the electrical work safely. The equipment was connected and made operational.</p><p>At the same time, the warehouse layout and material flow had to be reorganized. Brandon began learning how machines behaved, how materials and operators moved, where bottlenecks appeared, and how production problems affected commercial decisions.</p><p>Processing changed the economics of bulky materials. Material that had been too expensive to transport could be converted into forms that were easier to ship economically, increasing the range the company could handle.</p></Copy><Flow items={["IDENTIFY POWER PROBLEM","FIND TRANSFORMER","HIRE ELECTRICIAN","CONNECT EQUIPMENT","REORGANIZE FLOW","LEARN PRODUCTION"]}/><blockquote>PROCESSING DID NOT JUST ADD EQUIPMENT.<br/><strong>IT CHANGED WHAT THE BUSINESS WAS CAPABLE OF DOING.</strong></blockquote></section>

  <section className={`${styles.section} ${styles.scale}`}><Label>05 / SCALE</Label><h2>THEN I MADE THE MISTAKE<br/><em>OF GROWING TOO FAST.</em></h2><Narrative id="chapter8"/><Copy><p>The first operation worked well enough that Brandon believed more capacity could create more growth. The logic appeared straightforward.</p></Copy><Flow items={["MORE EQUIPMENT","MORE CAPACITY","MORE MATERIAL","MORE REVENUE","MORE PROFIT"]}/><div className={styles.footprint}><div><strong>~6,000</strong><span>SQ FT</span></div><b>→</b><div><strong>~24,000</strong><span>SQ FT</span></div></div><Copy><p>The company added shredders, crushers, washing systems, and more automated processing capability. But manufacturing introduced problems trading had never required Brandon to manage: maintenance, worn blades, complex power requirements, machine spacing, production flow, repairs, downtime, and the need for experienced technical leadership.</p><p>Physical capacity grew faster than technical and organizational capability. Because Brandon lacked a deep engineering background and had not built strong enough plant leadership early enough, many problems returned to him personally.</p><p>Over roughly two years, he spent significant time disassembling equipment, studying systems, troubleshooting, repairing, and reinstalling machines. The work made him more technically capable—but exposed a more important management lesson.</p></Copy><blockquote className={styles.principle}>CAPACITY IS NOT CAPABILITY.<br/><strong>BUYING EQUIPMENT DOES NOT CREATE THE ORGANIZATION REQUIRED TO OPERATE IT.</strong></blockquote><Copy><p>The mistake was not entering manufacturing. It was scaling physical capacity faster than the company built the technical systems, people, and management capability required to support it.</p></Copy></section>

  <section className={`${styles.section} ${styles.maturity}`}><Label>THE COMPANY AT SCALE</Label><h2>WHAT STARTED AS A SMALL TRADING IDEA<br/><em>HAD BECOME A REAL OPERATING BUSINESS.</em></h2><Narrative id="chapter9"/><Copy><p>At maturity, B.R. International was managing many interdependent functions at once.</p></Copy><div className={styles.constraints}>{functions.map(x=><span key={x}>{x}</span>)}</div><div className={styles.stats}><div><strong>~30–40</strong><span>U.S. SUPPLIERS</span></div><div><strong>~15</strong><span>EMPLOYEES</span></div><div><strong>~$3M</strong><span>NORMAL PEAK-YEAR REVENUE</span></div></div><blockquote>SUPPLY, CUSTOMERS, LOGISTICS, CASH FLOW, OPERATIONS, PEOPLE, AND RISK<br/><strong>ALL AFFECTED ONE ANOTHER.</strong></blockquote></section>

  <section className={`${styles.section} ${styles.pressure}`}><Label>06 / CRITICAL MOMENTS</Label><h2>BUSINESS IS WHAT HAPPENS<br/><em>WHEN THE PLAN BREAKS.</em></h2>
   <article className={styles.eva}><div className={styles.momentNo}>01</div><div><Label>EVA / MARKET VALIDATION</Label><h3>DON’T BUY FIRST<br/>AND LOOK FOR A CUSTOMER LATER.</h3><Narrative id="eva"/><Copy><p>B.R. International identified an opportunity involving EVA material. Rather than purchasing immediately because the supplier opportunity looked attractive, Brandon investigated the customer side first.</p><p>He validated demand in Malaysia, confirmed the price range the market could support, and worked backward from customer economics. Only after understanding the likely exit did the company commit.</p><p>The importance was not only the transaction’s size. It proved that a sourcing opportunity is not automatically a business opportunity; the downstream market must support the upstream decision.</p></Copy></div><div className={styles.momentEvidence}><strong>~20</strong><span>CONTAINERS</span><strong>~400+</strong><span>TONS</span></div><blockquote>VALIDATE THE EXIT<br/><strong>BEFORE COMMITTING TO THE BUY.</strong></blockquote></article>
   <article className={styles.abs}><div className={styles.momentNo}>02</div><div><Label>ABS VS. PS / HIPS</Label><h3>DON’T LET THE LABEL<br/><em>REPLACE YOUR OWN JUDGMENT.</em></h3><Narrative id="abs"/><Copy><p>A supplier represented a material as ABS. Something did not look right. Based on years of handling plastics, its physical behavior, burn characteristics, and smell suggested PS/HIPS instead.</p><p>Brandon did not treat his judgment as final proof. He separated samples and sought additional customer and professional verification. Later verification supported his original concern.</p><p>The lesson was not that Brandon had become a laboratory technician. Hands-on product knowledge had become part of his commercial judgment. A supplier label is information—not a substitute for verification when something does not make sense.</p></Copy></div><div className={styles.materialConflict}><strong>PRODUCT KNOWLEDGE</strong><b>+</b><strong>COMMERCIAL JUDGMENT</strong><b>+</b><strong>VERIFICATION</strong></div></article>
   <article className={styles.default}><div className={styles.momentNo}>03</div><div><Label>FOUR-CONTAINER CUSTOMER DEFAULT</Label><h3>THE FIRST MISTAKE<br/><em>WAS MINE.</em></h3><Narrative id="customerDefault"/><Copy><p>B.R. International normally required full prepayment. For one transaction, Brandon relaxed that discipline. The customer paid approximately a 50% deposit, four containers were shipped, and then the customer disappeared or defaulted while the cargo was already moving internationally.</p><p>The first problem was not how to rescue the shipment. Brandon had already weakened a commercial rule designed to protect the company.</p><p>Once the mistake existed, the focus shifted to minimizing damage. Brandon immediately used the company’s market relationships to find another buyer. An alternative customer was identified in Southeast Asia and the cargo was redirected.</p><p>The replacement transaction required an approximate 15–20% discount plus diversion and transshipment expense. The outcome was not ideal, but it prevented a much larger potential loss.</p></Copy></div><div className={styles.defaultStats}><div><strong>~50%</strong><span>DEPOSIT</span></div><div><strong>4</strong><span>CONTAINERS MOVING</span></div><div><strong>~15–20%</strong><span>DISCOUNT + DIVERSION COST</span></div></div><div className={styles.twoLessons}><p><span>THE ORIGINAL MISTAKE</span>WEAKENING MY OWN PAYMENT DISCIPLINE.</p><p><span>AFTER THE MISTAKE</span>SPEED, NETWORK, AND COMMERCIAL FLEXIBILITY PROTECTED THE BEST REMAINING OUTCOME.</p></div></article>
  </section>

  <section className={styles.section}><Label>07 / COMPLEXITY</Label><h2>THE BUSINESS WAS GROWING.<br/><em>THE SYSTEMS WERE NOT GROWING FAST ENOUGH.</em></h2><Narrative id="chapter11"/><Copy><p>In the beginning, Brandon could personally solve most problems. He knew the customers and suppliers. If a shipment had a problem, a machine broke, sourcing changed, or cash flow needed attention, he became involved.</p><p>That worked while the business was smaller. As it expanded, more revenue meant more transactions; more processing meant more equipment; more equipment meant more maintenance; more employees meant more management; and more inventory and shipments meant more cash-flow exposure.</p><p>The company had built capacity, but management systems, technical leadership, delegation, and operating processes had not matured at the same speed.</p></Copy><blockquote className={styles.principle}>A FOUNDER CAN START AS THE SYSTEM.<br/><strong>A COMPANY CANNOT SCALE IF THE FOUNDER REMAINS THE SYSTEM.</strong></blockquote></section>

  <section className={`${styles.section} ${styles.ending}`}><Label>08 / THE FINAL DECISION</Label><h2>THE COMPANY ENDED.<br/><em>THE EXPERIENCE DIDN’T.</em></h2><Narrative id="chapter12"/><Copy><p>By 2025, several pressures converged. The recycling market weakened. Low virgin-resin prices pressured recycled-material economics. Customer demand and margins became more difficult.</p><p>At the same time, equipment required continued maintenance and repair. Factory economics were harder to justify. The operating burden was increasing while the commercial environment became less attractive.</p><p>The question changed from “How do I grow this company?” to “Does continuing to put more money and personal energy into this still make economic sense?”</p><p>After seven years, stopping was extremely difficult. The company represented work, relationships, money, identity, and personal effort. But continuing only because so much had already been invested would create another mistake.</p></Copy><div className={styles.convergence}><div>{pressures.map(x=><span key={x}>{x}</span>)}</div><b>→</b><strong>CONTINUE<br/>OR STOP?</strong></div><blockquote className={styles.principle}>CONTINUING BECAUSE I HAD ALREADY SPENT<br/>SEVEN YEARS BUILDING IT<br/><strong>WOULD HAVE BEEN SUNK-COST THINKING,<br/>NOT PERSISTENCE.</strong></blockquote><Copy><p>The decision did not erase what had been built. It forced Brandon to separate persistence from attachment. Persistence means continuing when fundamentals justify the effort. Sunk-cost thinking means continuing because walking away feels emotionally harder than accepting what the economics are saying.</p></Copy></section>

  <section className={styles.section}><Label>09 / WHAT THE EXPERIENCE REQUIRED</Label><h2>SEVEN YEARS.<br/><em>MORE THAN ONE FUNCTION.</em></h2><div className={styles.solvedGrid}>{solved.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

  <section className={`${styles.section} ${styles.lessons}`}><Label>10 / LESSONS</Label><h2>I LEARNED HOW TO BUILD.<br/><em>BUT BUILDING WAS ONLY HALF THE LESSON.</em></h2><div className={styles.lessonList}>{lessons.map(([n,title,text])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

  <section className={`${styles.section} ${styles.final}`}><Label>CASE 01 / FINAL REFLECTION</Label><h2>I LEARNED<br/>HOW TO BUILD.</h2><div className={styles.finalBuild}><p>FROM ZERO.</p><p>FROM LIMITED RESOURCES.</p><p>ACROSS SUPPLY, CUSTOMERS, LOGISTICS, OPERATIONS, AND MARKETS.</p></div><p>I ALSO LEARNED THAT SUSTAINABLE GROWTH REQUIRES MORE THAN ENTREPRENEURIAL DRIVE.</p><div className={styles.finalPillars}><strong>SYSTEMS.</strong><strong>DISCIPLINE.</strong><strong>TECHNICAL CAPABILITY.</strong><strong>LEADERSHIP.</strong><strong>THE RIGHT TEAM.</strong></div><Copy><p>B.R. International taught Brandon how to identify opportunities, build supplier relationships, execute cross-border business, solve operational problems, and make decisions under uncertainty.</p><p>Its growth also exposed the limits of founder-led execution and the importance of organizational capability. That combination—what worked and what did not—is what makes the seven-year experience valuable today.</p></Copy><Narrative id="final"/><nav className={styles.caseNav}><a href="/work">← <span>BACK TO WORK</span></a><span className={styles.nextDisabled}><span>NEXT CASE</span> →</span></nav></section>
 </div>
 </main>}
